# Creating a logistic regression to predict absenteeism

## Import the relevant libraries

In [1]:
# import the relevant libraries
import pandas as pd
import numpy as np

## Load the data

In [2]:
# load the preprocessed CSV data
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
# eyeball the data
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

## Create the targets

In [4]:
# find the median of 'Absenteeism Time in Hours'
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
# create targets for our logistic regression
# they have to be categories and we must find a way to say if someone is 'being absent too much' or not
# what we've decided to do is to take the median of the dataset as a cut-off line
# in this way the dataset will be balanced (there will be roughly equal number of 0s and 1s for the logistic regression)
# as balancing is a great problem for ML, this will work great for us
# alternatively, if we had more data, we could have found other ways to deal with the issue 
# for instance, we could have assigned some arbitrary value as a cut-off line, instead of the median

# note that what line does is to assign 1 to anyone who has been absent 4 hours or more (more than 3 hours)
# that is the equivalent of taking half a day off

# initial code from the lecture
# targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

# parameterized code
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
# eyeball the targets
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [7]:
# create a Series in the original data frame that will contain the targets for the regression
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
# check what happened
# maybe manually see how the targets were created
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

## A comment on the targets

In [9]:
# check if dataset is balanced (what % of targets are 1s)
# targets.sum() will give us the number of 1s that there are
# the shape[0] will give us the length of the targets array
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
# create a checkpoint by dropping the unnecessary variables
# also drop the variables we 'eliminated' after exploring the weights
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [11]:
# check if the line above is a checkpoint :)

# if data_with_targets is data_preprocessed = True, then the two are pointing to the same object
# if it is False, then the two variables are completely different and this is in fact a checkpoint
data_with_targets is data_preprocessed

False

In [12]:
# check what's inside
data_with_targets.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0

## Select the inputs for the regression

In [13]:
data_with_targets.shape

(700, 12)

In [14]:
# Selects all rows and all columns until 14 (excluding)
data_with_targets.iloc[:,:14]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0
5,0,0,0,1,7,179,38,31,0,0,0,0
6,0,0,0,1,7,361,28,27,0,1,4,1
7,0,0,0,1,7,260,36,23,0,4,0,1
8,0,0,1,0,7,155,34,25,0,2,0,1
9,0,0,0,1,7,235,37,29,1,1,1,1
10,1,0,0,0,7,260,36,23,0,4,0,1
11,1,0,0,0,7,260,36,23,0,4,0,1
12,1,0,0,0,7,260,36,23,0,4,0,1
13,1,0,0,0,7,179,38,31,0,0,0,0
14,0,0,0,1,7,179,38,31,0,0,0,1
15,1,0,0,0,7,246,41,23,0,0,0,1
16,0,0,0,1,7,179,38,31,0,0,0,0
17,0,0,1,0,7,179,38,31,0,0,0,1
18,1,0,0,0,7,189,33,25,0,2,2,1
19,0,0,0,1,8,248,47,32,0,2,1,0
20,1,0,0,0,8,330,28,25,1,0,0,1
21,1,0,0,0,8,179,38,31,0,0,0,0
22,1,0,0,0,8,361,28,27,0,1,4,1
23,0,0,0,1,8,260,36,23,0,4,0,1
24,0,0,1,0,8,289,33,30,0,2,1,1
25,0,0,0,1,8,361,28,27,0,1,4,1
26,0,0,0,1,8,289,33,30,0,2,1,0
27,0,0,0,1,8,157,29,22,0,0,0,1
28,0,0,1,0,8,289,33,30,0,2,1,1
29,0,0,0,1,8,179,38,31,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,155,34,25,0,2,0,1
671,0,0,1,0,4,225,28,24,0,1,2,1
672,1,0,0,0,4,118,50,31,0,1,0,0
673,0,0,0,1,4,179,30,19,1,0,0,0
674,0,0,0,1,5,235,37,29,1,1,1,1
675,0,0,1,0,5,225,41,28,1,2,2,0
676,0,0,0,1,5,235,32,25,1,0,0,0
677,1,0,0,0,5,118,37,28,0,0,0,0
678,0,0,0,1,5,235,43,38,0,1,0,1
679,1,0,0,0,5,179,30,19,1,0,0,0
680,0,0,0,1,5,291,40,25,0,1,1,0
681,1,0,0,0,5,225,41,28,1,2,2,1
682,0,0,1,0,5,300,43,25,0,2,1,1
683,0,0,0,1,5,225,41,28,1,2,2,1
684,0,0,0,1,5,179,30,19,1,0,0,0
685,0,0,0,1,5,118,50,31,0,1,0,0
686,1,0,0,0,5,118,50,31,0,1,0,0
687,0,0,0,1,5,118,37,28,0,0,0,0
688,0,0,0,0,5,118,50,31,0,1,0,0
689,0,0,0,1,5,179,30,19,1,0,0,0
690,0,0,0,0,5,378,36,21,0,2,4,0
691,0,1,0,0,5,179,40,22,1,2,0,0
692,1,0,0,0,5,155,34,25,0,2,0,1
693,1,0,0,0,5,235,32,25,1,0,0,1
694,0,0,0,1,5,291,40,25,0,1,1,1
695,1,0,0,0,5,179,40,22,1,2,0,1
696,1,0,0,0,5,225,28,24,0,1,2,0
697,1,0,0,0,5,330,28,25,1,0,0,1
698,0,0,0,1,5,235,32,25,1,0,0,0
699,0,0,0,1,5,291,40,25,0,1,1,0

In [15]:
# Selects all rows and all columns but the last one (basically the same operation)
data_with_targets.iloc[:,:-1]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,7,289,33,30,0,2,1
1,0,0,0,0,7,118,50,31,0,1,0
2,0,0,0,1,7,179,38,31,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0
4,0,0,0,1,7,289,33,30,0,2,1
5,0,0,0,1,7,179,38,31,0,0,0
6,0,0,0,1,7,361,28,27,0,1,4
7,0,0,0,1,7,260,36,23,0,4,0
8,0,0,1,0,7,155,34,25,0,2,0
9,0,0,0,1,7,235,37,29,1,1,1
10,1,0,0,0,7,260,36,23,0,4,0
11,1,0,0,0,7,260,36,23,0,4,0
12,1,0,0,0,7,260,36,23,0,4,0
13,1,0,0,0,7,179,38,31,0,0,0
14,0,0,0,1,7,179,38,31,0,0,0
15,1,0,0,0,7,246,41,23,0,0,0
16,0,0,0,1,7,179,38,31,0,0,0
17,0,0,1,0,7,179,38,31,0,0,0
18,1,0,0,0,7,189,33,25,0,2,2
19,0,0,0,1,8,248,47,32,0,2,1
20,1,0,0,0,8,330,28,25,1,0,0
21,1,0,0,0,8,179,38,31,0,0,0
22,1,0,0,0,8,361,28,27,0,1,4
23,0,0,0,1,8,260,36,23,0,4,0
24,0,0,1,0,8,289,33,30,0,2,1
25,0,0,0,1,8,361,28,27,0,1,4
26,0,0,0,1,8,289,33,30,0,2,1
27,0,0,0,1,8,157,29,22,0,0,0
28,0,0,1,0,8,289,33,30,0,2,1
29,0,0,0,1,8,179,38,31,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,155,34,25,0,2,0
671,0,0,1,0,4,225,28,24,0,1,2
672,1,0,0,0,4,118,50,31,0,1,0
673,0,0,0,1,4,179,30,19,1,0,0
674,0,0,0,1,5,235,37,29,1,1,1
675,0,0,1,0,5,225,41,28,1,2,2
676,0,0,0,1,5,235,32,25,1,0,0
677,1,0,0,0,5,118,37,28,0,0,0
678,0,0,0,1,5,235,43,38,0,1,0
679,1,0,0,0,5,179,30,19,1,0,0
680,0,0,0,1,5,291,40,25,0,1,1
681,1,0,0,0,5,225,41,28,1,2,2
682,0,0,1,0,5,300,43,25,0,2,1
683,0,0,0,1,5,225,41,28,1,2,2
684,0,0,0,1,5,179,30,19,1,0,0
685,0,0,0,1,5,118,50,31,0,1,0
686,1,0,0,0,5,118,50,31,0,1,0
687,0,0,0,1,5,118,37,28,0,0,0
688,0,0,0,0,5,118,50,31,0,1,0
689,0,0,0,1,5,179,30,19,1,0,0
690,0,0,0,0,5,378,36,21,0,2,4
691,0,1,0,0,5,179,40,22,1,2,0
692,1,0,0,0,5,155,34,25,0,2,0
693,1,0,0,0,5,235,32,25,1,0,0
694,0,0,0,1,5,291,40,25,0,1,1
695,1,0,0,0,5,179,40,22,1,2,0
696,1,0,0,0,5,225,28,24,0,1,2
697,1,0,0,0,5,330,28,25,1,0,0
698,0,0,0,1,5,235,32,25,1,0,0
699,0,0,0,1,5,291,40,25,0,1,1

In [16]:
# Create a variable that will contain the inputs (everything without the targets)
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [17]:
# standardize the inputs

# standardization is one of the most common preprocessing tools
# since data of different magnitude (scale) can be biased towards high values,
# we want all inputs to be of similar magnitude
# this is a peculiarity of machine learning in general - most (but not all) algorithms do badly with unscaled data

# a very useful module we can use is StandardScaler 
# it has much more capabilities than the straightforward 'preprocessing' method
from sklearn.preprocessing import StandardScaler


# we will create a variable that will contain the scaling information for this particular dataset
# here's the full documentation: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

# define scaler as an object
absenteeism_scaler = StandardScaler()

In [18]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [19]:
# check what are all columns that we've got
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [20]:
# choose the columns to scale
# we later augmented this code and put it in comments
# columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']
    
# select the columns to omit
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [21]:
# create the columns to scale, based on the columns to omit
# use list comprehension to iterate over the list
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [22]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)

In [23]:
# fit the data (calculate mean and standard deviation); they are automatically stored inside the object 
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age', 'Body Mass Index', 'Children', 'Pets'],
       copy=None, with_mean=None, with_std=None)

In [24]:
# standardizes the data, using the transform method 
# in the last line, we fitted the data - in other words
# we found the internal parameters of a model that will be used to transform data. 
# transforming applies these parameters to our data
# note that when you get new data, you can just call 'scaler' again and transform it in the same way as now
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [25]:
# the scaled_inputs are now an ndarray, because sklearn works with ndarrays
scaled_inputs

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,0,0,0,1,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,0,0,0,0,0.182726,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,1,0,0,0,0.182726,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,0,0,0,1,0.182726,1.005844,-0.536062,0.767431,0,0.880469,0.268487
5,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
6,0,0,0,1,0.182726,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
7,0,0,0,1,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
8,0,0,1,0,0.182726,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
9,0,0,0,1,0.182726,0.190942,0.091435,0.532229,1,-0.019280,0.268487
10,1,0,0,0,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
11,1,0,0,0,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
12,1,0,0,0,0.182726,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
13,1,0,0,0,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
14,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
15,1,0,0,0,0.182726,0.356940,0.718933,-0.878984,0,-0.919030,-0.589690
16,0,0,0,1,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
17,0,0,1,0,0.182726,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
18,1,0,0,0,0.182726,-0.503235,-0.536062,-0.408580,0,0.880469,1.126663
19,0,0,0,1,0.468236,0.387122,1.660180,1.237836,0,0.880469,0.268487
20,1,0,0,0,0.468236,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
21,1,0,0,0,0.468236,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
22,1,0,0,0,0.468236,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
23,0,0,0,1,0.468236,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
24,0,0,1,0,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
25,0,0,0,1,0.468236,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
26,0,0,0,1,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
27,0,0,0,1,0.468236,-0.986140,-1.163560,-1.114186,0,-0.919030,-0.589690
28,0,0,1,0,0.468236,1.005844,-0.536062,0.767431,0,0.880469,0.268487
29,0,0,0,1,0.468236,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,-0.673803,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
671,0,0,1,0,-0.673803,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
672,1,0,0,0,-0.673803,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
673,0,0,0,1,-0.673803,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
674,0,0,0,1,-0.388293,0.190942,0.091435,0.532229,1,-0.019280,0.268487
675,0,0,1,0,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
676,0,0,0,1,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
677,1,0,0,0,-0.388293,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
678,0,0,0,1,-0.388293,0.190942,1.032682,2.649049,0,-0.019280,-0.589690
679,1,0,0,0,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
680,0,0,0,1,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
681,1,0,0,0,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
682,0,0,1,0,-0.388293,1.171843,1.032682,-0.408580,0,0.880469,0.268487
683,0,0,0,1,-0.388293,0.040034,0.718933,0.297027,1,0.880469,1.126663
684,0,0,0,1,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
685,0,0,0,1,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
686,1,0,0,0,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
687,0,0,0,1,-0.388293,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
688,0,0,0,0,-0.388293,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
689,0,0,0,1,-0.388293,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
690,0,0,0,0,-0.388293,2.348925,-0.065439,-1.349389,0,0.880469,2.843016
691,0,1,0,0,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
692,1,0,0,0,-0.388293,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
693,1,0,0,0,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
694,0,0,0,1,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
695,1,0,0,0,-0.388293,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
696,1,0,0,0,-0.388293,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,1,0,0,0,-0.388293,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
698,0,0,0,1,-0.388293,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
699,0,0,0,1,-0.388293,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [26]:
# check the shape of the inputs
scaled_inputs.shape

(700, 11)

## Split the data into train & test and shuffle

### Import the relevant module

In [27]:
# import train_test_split so we can split our data into train and test
from sklearn.model_selection import train_test_split

### Split

In [28]:
# check how this method works
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 214         0         0         0         0    -0.388293
 171         0         0         0         1    -0.959313
 564         0         0         1         0     1.610276
 687         0         0         0         1    -0.388293
 95          0         0         0         1     1.324766
 427         1         0         0         0    -0.388293
 592         0         0         0         1    -1.244823
 112         0         0         0         1     1.610276
 425         1         0         0         0    -0.388293
 458         1         0         0         0    -0.102784
 44          0         0         0         1     0.753746
 598         0         0         0         1    -1.244823
 183         0         0         0         1    -0.959313
 181         0         0         0         1    -0.959313
 388         0         0         0         1    -1.244823
 616         0         0         0         1    -1.244823
 276         0         0         0         0     0.753746
 254         0         0         0         1     0.468236
 201         1         0         0         0    -0.673803
 146         0         0         0         1    -1.244823
 361         1         0         0         0    -1.530333
 309         0         0         0         1     1.039256
 615         0         0         0         1    -1.244823
 644         0         0         0         1    -0.959313
 417         0         0         0         1    -0.673803
 684         0         0         0         1    -0.388293
 225         1         0         0         0    -0.102784
 470         0         0         0         1     0.182726
 47          0         0         0         1     0.753746
 416         0         0         0         1    -0.673803
 ..        ...       ...       ...       ...          ...
 537         0         0         0         1     1.324766
 111         0         0         1         0     1.610276
 453         0         0         0         1    -0.102784
 669         0         0         0         1    -0.673803
 463         1         0         0         0     0.182726
 502         0         0         0         1     0.753746
 465         0         0         0         1     0.182726
 89          1         0         0         0     1.324766
 286         0         0         0         1     0.753746
 660         1         0         0         0    -0.673803
 386         0         0         0         1    -1.244823
 573         0         0         0         1    -1.530333
 244         1         0         0         0     0.182726
 109         0         0         0         1     1.610276
 99          0         0         1         0     1.610276
 266         0         0         0         1     0.468236
 567         0         0         0         1     1.610276
 11          1         0         0         0     0.182726
 495         0         0         0         1     0.753746
 448         0         0         0         1    -0.102784
 285         0         0         0         0     0.753746
 650         0         0         0         1    -0.959313
 179         1         0         0         0    -0.959313
 94          0         0         0         1     1.324766
 596         1         0         0         0    -1.244823
 170         0         0         0         1    -0.959313
 371         1         0         0         0    -1.244823
 242         0         0         0         1     0.182726
 674         0         0         0         1    -0.388293
 334         1         0         0         0     1.324766

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 214                1.624567 -1.320435        -0.408580          1 -0.919030
 171                0.040034 -1.320435        -0.643782          0 -0.019280
 564                0.160760 -0.849811        -1.349389          1 -0.019280
 687               -1.574681  0.091435         0.297027          0 -0.919030
 95                 0.040034 -1.320435        -0.643782          0 -0.019280
 427                2.213108 -0.849811        -0.408580          0  1.780219
 592                0.040034  0.718933         0.297027          1  0.880469
 112                0.040034 -1.320435        -0.643782          0 -0.019280
 425                0.190942  1.032682         2.649049          0 -0.019280
 458                1.624567 -1.320435        -0.408580          1 -0.919030
 44                -1.016322 -0.379188        -0.408580          0  0.880469
 598               -0.654143  0.248310         1.002633          0 -0.919030
 183                0.040034 -1.320435        -0.643782          0 -0.019280
 181                0.040034 -1.320435        -0.643782          0 -0.019280
 388               -0.654143  0.248310         1.002633          0 -0.919030
 616               -0.654143  0.248310         1.002633          0 -0.919030
 276                0.130578  0.405184         1.943442          0  0.880469
 254                1.005844 -0.536062         0.767431          0  0.880469
 201                1.005844 -0.536062         0.767431          0  0.880469
 146                0.040034 -1.320435        -0.643782          0 -0.019280
 361                0.190942  0.091435         0.532229          1 -0.019280
 309               -1.574681  2.130803         1.002633          0 -0.019280
 615               -0.654143  0.248310         1.002633          0 -0.919030
 644               -0.654143 -1.006686        -1.819793          1 -0.919030
 417                1.624567 -1.320435        -0.408580          1 -0.919030
 684               -0.654143 -1.006686        -1.819793          1 -0.919030
 225               -0.654143  0.248310         1.002633          0 -0.919030
 470                0.356940  0.718933        -0.878984          0 -0.919030
 47                 1.036026  0.562059        -0.408580          0 -0.019280
 416                0.387122  1.660180         1.237836          0  0.880469
 ..                      ...       ...              ...        ...       ...
 537                1.005844 -0.536062         0.767431          0  0.880469
 111                0.356940  0.718933        -0.878984          0 -0.919030
 453                0.040034 -1.320435        -0.643782          0 -0.019280
 669               -0.654143 -1.006686        -1.819793          1 -0.919030
 463                0.688938 -0.536062        -0.408580          1 -0.919030
 502               -0.654143  0.248310         1.002633          0 -0.919030
 465               -1.574681  0.091435         0.297027          0 -0.919030
 89                -1.016322 -0.379188        -0.408580          0  0.880469
 286                1.036026  0.562059        -0.408580          0 -0.019280
 660                2.213108 -0.849811        -0.408580          0  1.780219
 386               -0.654143  0.248310         1.002633          0 -0.919030
 573               -0.654143  0.562059        -1.114186          1  0.880469
 244                1.624567 -1.320435        -0.408580          1 -0.919030
 109                2.092381 -1.320435         0.061825          0 -0.019280
 99                -1.574681  0.091435         0.297027          0 -0.919030
 266               -1.574681  2.130803         1.002633          0 -0.019280
 567                0.040034 -1.320435        -0.643782          0 -0.019280
 11                 0.568211 -0.065439        -0.878984          0  2.679969
 495                0.356940  0.718933        -0.878984          0 -0.919030
 448               -0.654143  0.248310         1.002633          0 -0.919030
 285                0.190942  1.032682         2.649049          0 -0.019280
 650               -0.654143  0.248310         1.002633          0 -0.919030
 179               -0.654143  0.248310         1.002633          0 -0.919030
 94                 0.387122  1.660180         1.237836          0  0.880469
 596                0.040034 -1.320435        -0.643782          0 -0.019280
 170                0.568211 -0.065439        -0.878984          0  2.679969
 371                0.040034 -1.320435        -0.643782          0 -0.019280
 242               -1.016322 -0.379188        -0.408580          0  0.880469
 674                0.190942  0.091435         0.532229          1 -0.019280
 334                0.568211 -0.065439        -0.878984          0  2.679969

          Pets
 214 -0.589690
 171  1.126663
 564  6.275721
 687 -0.589690
 95   1.126663
 427 -0.589690
 592  1.126663
 112  1.126663
 425 -0.589690
 458 -0.589690
 44  -0.589690
 598 -0.589690
 183  1.126663
 181  1.126663
 388 -0.589690
 616 -0.589690
 276  1.126663
 254  0.268487
 201  0.268487
 146  1.126663
 361  0.268487
 309 -0.589690
 615 -0.589690
 644 -0.589690
 417 -0.589690
 684 -0.589690
 225 -0.589690
 470 -0.589690
 47   0.268487
 416  0.268487
 ..        ...
 537  0.268487
 111 -0.589690
 453  1.126663
 669 -0.589690
 463 -0.589690
 502 -0.589690
 465 -0.589690
 89  -0.589690
 286  0.268487
 660 -0.589690
 386 -0.589690
 573 -0.589690
 244 -0.589690
 109  2.843016
 99  -0.589690
 266 -0.589690
 567  1.126663
 11  -0.589690
 495 -0.589690
 448 -0.589690
 285 -0.589690
 650 -0.589690
 179 -0.589690
 94   0.268487
 596  1.126663
 170 -0.589690
 371  1.126663
 242 -0.589690
 674  0.268487
 334 -0.589690

 [525 rows x 11 columns],
      Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 228         1         0         0         0    -0.102784
 600         1         0         0         0    -1.244823
 8           0         0         1         0     0.182726
 628         0         0         0         1    -0.959313
 233         1         0         0         0    -0.102784
 137         0         0         0         1    -1.244823
 287         1         0         0         0     0.753746
 38          0         0         0         1     0.468236
 610         0         0         0         1    -1.244823
 637         1         0         0         0    -0.959313
 12          1         0         0         0     0.182726
 236         0         0         1         0     0.182726
 306         0         0         0         1     1.039256
 198         0         0         1         0    -0.673803
 173         1         0         0         0    -0.959313
 527         0         0         0         1     1.039256
 489         0         0         0         1     0.468236
 48          0         0         0         1     0.753746
 404         1         0         0         0    -0.959313
 124         0         0         0         1    -1.530333
 98          0         0         0         1     1.610276
 662         0         0         0         1    -0.673803
 521         1         0         0         0     1.039256
 574         1         0         0         0    -1.530333
 384         1         0         0         0    -1.244823
 55          0         0         0         0     0.753746
 401         0         0         1         0    -0.959313
 114         0         0         1         0    -1.530333
 373         0         0         0         1    -1.244823
 153         0         0         0         1    -1.244823
 ..        ...       ...       ...       ...          ...
 576         1         0         0         0    -1.530333
 433         1         0         0         0    -0.388293
 58          0         0         0         0     0.753746
 103         0         0         0         1     1.610276
 627         0         0         0         1    -0.959313
 279         1         0         0         0     0.753746
 220         0         0         1         0    -0.102784
 577         0         0         1         0    -1.530333
 485         0         0         0         1     0.468236
 381         0         0         0         1    -1.244823
 364         1         0         0         0    -1.530333
 504         0         0         0         1     0.753746
 91          0         0         1         0     1.324766
 150         0         0         0         1    -1.244823
 168         1         0         0         0    -0.959313
 235         0         0         0         1    -0.102784
 362         0         0         0         1    -1.530333
 257         1         0         0         0     0.468236
 269         1         0         0         0     0.468236
 621         0         0         0         1    -0.959313
 245         0         0         0         1     0.182726
 28          0         0         1         0     0.468236
 300         0         0         0         0     1.039256
 41          0         0         0         1     0.753746
 177         1         0         0         0    -0.959313
 132         0         0         0         1    -1.530333
 341         0         0         0         1     1.610276
 2           0         0         0         1     0.182726
 602         0         0         0         1    -1.244823
 290         0         0         0         1     1.039256

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 228               -1.574681  2.130803         1.002633          0 -0.019280
 600               -0.654143 -1.006686        -1.819793          1 -0.919030
 8                 -1.016322 -0.379188        -0.408580          0  0.880469
 628                0.190942 -0.692937        -0.408580          1 -0.919030
 233               -0.654143  0.248310         1.002633          0 -0.919030
 137               -0.578689 -1.477309        -1.349389          0 -0.919030
 287                1.036026  0.562059        -0.408580          0 -0.019280
 38                 0.190942  1.817054         1.473038          0 -0.019280
 610               -0.654143  0.248310         1.002633          0 -0.919030
 637                0.040034 -1.320435        -0.643782          0 -0.019280
 12                 0.568211 -0.065439        -0.878984          0  2.679969
 236               -1.016322 -0.379188        -0.408580          0  0.880469
 306               -1.574681  2.130803         1.002633          0 -0.019280
 198                1.005844 -0.536062         0.767431          0  0.880469
 173               -0.654143  0.248310         1.002633          0 -0.919030
 527               -0.503235 -0.536062        -0.408580          0  0.880469
 489                1.624567 -1.320435        -0.408580          1 -0.919030
 48                 0.568211 -0.065439        -0.878984          0  2.679969
 404               -1.574681  2.130803         1.002633          0 -0.019280
 124               -1.574681  0.091435         0.297027          0 -0.919030
 98                 0.387122  1.660180         1.237836          0  0.880469
 662               -1.574681  2.130803         1.002633          0 -0.019280
 521                0.085306  3.385799        -1.114186          0  0.880469
 574               -0.654143 -1.006686        -1.819793          1 -0.919030
 384               -0.986140 -1.163560        -1.114186          0 -0.919030
 55                -1.574681  2.130803         1.002633          0 -0.019280
 401                0.190942  0.091435         0.532229          1 -0.019280
 114               -1.574681  0.091435         0.297027          0 -0.919030
 373                0.568211 -0.065439        -0.878984          0  2.679969
 153                0.040034 -1.320435        -0.643782          0 -0.019280
 ..                      ...       ...              ...        ...       ...
 576                1.005844  1.973929         2.178644          0 -0.919030
 433               -0.654143  0.562059        -1.114186          1  0.880469
 58                 2.213108 -0.849811        -0.408580          0  1.780219
 103                0.568211 -0.065439        -0.878984          0  2.679969
 627               -0.654143 -1.006686        -1.819793          1 -0.919030
 279                0.356940  0.718933        -0.878984          0 -0.919030
 220                0.356940  0.718933        -0.878984          0 -0.919030
 577               -0.654143  0.562059        -1.114186          1  0.880469
 485                0.190942  1.032682         2.649049          0 -0.019280
 381               -0.654143  0.248310         1.002633          0 -0.919030
 364                1.036026  0.562059        -0.408580          0 -0.019280
 504               -0.654143 -1.006686        -1.819793          1 -0.919030
 91                -0.654143  0.562059        -1.114186          1  0.880469
 150                0.040034 -1.320435        -0.643782          0 -0.019280
 168                1.005844 -0.536062         0.767431          0  0.880469
 235                0.040034 -1.320435        -0.643782          0 -0.019280
 362               -1.016322 -0.379188        -0.408580          0  0.880469
 257                1.171843  1.032682        -0.408580          0  0.880469
 269               -0.578689 -1.477309        -1.349389          0 -0.919030
 621                0.387122  1.660180         1.237836          0  0.880469
 245               -0.986140 -1.163560        -1.114186          0 -0.919030
 28                 1.005844 -0.536062         0.767431          0  0.880469
 300                0.190942  1.032682         2.649049          0 -0.019280
 41                -1.574681  0.091435         0.297027          0 -0.919030
 177                0.040034 -1.320435        -0.643782          0 -0.019280
 132               -0.578689 -1.477309        -1.349389          0 -0.919030
 341               -0.654143  0.248310         1.002633          0 -0.919030
 2                 -0.654143  0.248310         1.002633          0 -0.919030
 602               -0.654143  0.248310         1.002633          0 -0.919030
 290                0.190942  0.091435         0.532229          1 -0.019280

          Pets
 228 -0.589690
 600 -0.589690
 8   -0.589690
 628 -0.589690
 233 -0.589690
 137 -0.589690
 287  0.268487
 38   3.701192
 610 -0.589690
 637  1.126663
 12  -0.589690
 236 -0.589690
 306 -0.589690
 198  0.268487
 173 -0.589690
 527  1.126663
 489 -0.589690
 48  -0.589690
 404 -0.589690
 124 -0.589690
 98   0.268487
 662 -0.589690
 521  0.268487
 574 -0.589690
 384 -0.589690
 55  -0.589690
 401  0.268487
 114 -0.589690
 373 -0.589690
 153  1.126663
 ..        ...
 576  1.126663
 433 -0.589690
 58  -0.589690
 103 -0.589690
 627 -0.589690
 279 -0.589690
 220 -0.589690
 577 -0.589690
 485 -0.589690
 381 -0.589690
 364  0.268487
 504 -0.589690
 91  -0.589690
 150  1.126663
 168  0.268487
 235  1.126663
 362 -0.589690
 257  0.268487
 269 -0.589690
 621  0.268487
 245 -0.589690
 28   0.268487
 300 -0.589690
 41  -0.589690
 177  1.126663
 132 -0.589690
 341 -0.589690
 2   -0.589690
 602 -0.589690
 290  0.268487

 [175 rows x 11 columns],
 array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
        1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,

In [29]:
# declare 4 variables for the split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [30]:
# check the shape of the train inputs and targets
print (x_train.shape, y_train.shape)

(560, 11) (560,)

In [31]:
# check the shape of the test inputs and targets
print (x_test.shape, y_test.shape)

(140, 11) (140,)

## Logistic regression with sklearn

In [32]:
# import the LogReg model from sklearn
from sklearn.linear_model import LogisticRegression

# import the 'metrics' module, which includes important metrics we may want to use
from sklearn import metrics

### Training the model

In [33]:
# create a logistic regression object
reg = LogisticRegression()

In [34]:
# fit our train inputs
# that is basically the whole training part of the machine learning
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [35]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

0.775

### Manually check the accuracy

In [36]:
# find the model outputs according to our model
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [37]:
# compare them with the targets
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [38]:
# ACTUALLY compare the two variables
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

In [39]:
# find out in how many instances we predicted correctly
np.sum((model_outputs==y_train))

434

In [40]:
# get the total number of instances
model_outputs.shape[0]

560

In [41]:
# calculate the accuracy of the model
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.775

### Finding the intercept and coefficients

In [42]:
# get the intercept (bias) of our model
reg.intercept_

array([-1.46547112])

In [43]:
# get the coefficients (weights) of our model
reg.coef_

array([[ 2.62749942,  0.86338637,  2.96050661,  0.66390745,  0.15493732,
         0.59979822, -0.17245127,  0.27568526, -0.23452541,  0.34249662,
        -0.2775137 ]])

In [44]:
# check what were the names of our columns
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [45]:
# save the names of the columns in an ad-hoc variable
feature_name = unscaled_inputs.columns.values

In [46]:
# use the coefficients from this table (they will be exported later and will be used in Tableau)
# transpose the model coefficients (model.coef_) and throws them into a df (a vertical organization, so that they can be
# multiplied by certain matrices later) 
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table

              Feature name  Coefficient
0                 Reason_1     2.627499
1                 Reason_2     0.863386
2                 Reason_3     2.960507
3                 Reason_4     0.663907
4              Month Value     0.154937
5   Transportation Expense     0.599798
6                      Age    -0.172451
7          Body Mass Index     0.275685
8                Education    -0.234525
9                 Children     0.342497
10                    Pets    -0.277514

In [47]:
# do a little Python trick to move the intercept to the top of the summary table
# move all indices by 1
summary_table.index = summary_table.index + 1

# add the intercept at index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

# sort the df by index
summary_table = summary_table.sort_index()
summary_table

              Feature name  Coefficient
0                Intercept    -1.465471
1                 Reason_1     2.627499
2                 Reason_2     0.863386
3                 Reason_3     2.960507
4                 Reason_4     0.663907
5              Month Value     0.154937
6   Transportation Expense     0.599798
7                      Age    -0.172451
8          Body Mass Index     0.275685
9                Education    -0.234525
10                Children     0.342497
11                    Pets    -0.277514

## Interpreting the coefficients

In [48]:
# create a new Series called: 'Odds ratio' which will show the.. odds ratio of each feature
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [49]:
# display the df
summary_table

              Feature name  Coefficient  Odds_ratio
0                Intercept    -1.465471    0.230969
1                 Reason_1     2.627499   13.839121
2                 Reason_2     0.863386    2.371177
3                 Reason_3     2.960507   19.307751
4                 Reason_4     0.663907    1.942367
5              Month Value     0.154937    1.167585
6   Transportation Expense     0.599798    1.821751
7                      Age    -0.172451    0.841599
8          Body Mass Index     0.275685    1.317433
9                Education    -0.234525    0.790946
10                Children     0.342497    1.408460
11                    Pets    -0.277514    0.757665

In [50]:
# sort the table according to odds ratio
# note that by default, the sort_values method sorts values by 'ascending'
summary_table.sort_values('Odds_ratio', ascending=False)

              Feature name  Coefficient  Odds_ratio
3                 Reason_3     2.960507   19.307751
1                 Reason_1     2.627499   13.839121
2                 Reason_2     0.863386    2.371177
4                 Reason_4     0.663907    1.942367
6   Transportation Expense     0.599798    1.821751
10                Children     0.342497    1.408460
8          Body Mass Index     0.275685    1.317433
5              Month Value     0.154937    1.167585
7                      Age    -0.172451    0.841599
9                Education    -0.234525    0.790946
11                    Pets    -0.277514    0.757665
0                Intercept    -1.465471    0.230969

## Testing the model

In [51]:
# assess the test accuracy of the model
reg.score(x_test,y_test)

0.75

In [52]:
# find the predicted probabilities of each class
# the first column shows the probability of a particular observation to be 0, while the second one - to be 1
predicted_proba = reg.predict_proba(x_test)

# let's check that out
predicted_proba

array([[0.71221976, 0.28778024],
       [0.58760009, 0.41239991],
       [0.44337438, 0.55662562],
       [0.77903962, 0.22096038],
       [0.08458343, 0.91541657],
       [0.33103371, 0.66896629],
       [0.29792496, 0.70207504],
       [0.12956221, 0.87043779],
       [0.78307821, 0.21692179],
       [0.74708659, 0.25291341],
       [0.49514969, 0.50485031],
       [0.22640297, 0.77359703],
       [0.07030984, 0.92969016],
       [0.73504052, 0.26495948],
       [0.30533085, 0.69466915],
       [0.55035881, 0.44964119],
       [0.55027426, 0.44972574],
       [0.53930442, 0.46069558],
       [0.40117774, 0.59882226],
       [0.05320682, 0.94679318],
       [0.69874615, 0.30125385],
       [0.77903962, 0.22096038],
       [0.41634563, 0.58365437],
       [0.41634563, 0.58365437],
       [0.2412915 , 0.7587085 ],
       [0.74317087, 0.25682913],
       [0.51065194, 0.48934806],
       [0.85703303, 0.14296697],
       [0.19934235, 0.80065765],
       [0.77903962, 0.22096038],
       [0.62971577, 0.37028423],
       [0.31683213, 0.68316787],
       [0.31174245, 0.68825755],
       [0.47305759, 0.52694241],
       [0.77903962, 0.22096038],
       [0.46507358, 0.53492642],
       [0.77546993, 0.22453007],
       [0.25610763, 0.74389237],
       [0.59670727, 0.40329273],
       [0.39698373, 0.60301627],
       [0.78656024, 0.21343976],
       [0.54516654, 0.45483346],
       [0.7596912 , 0.2403088 ],
       [0.5611569 , 0.4388431 ],
       [0.17377065, 0.82622935],
       [0.42142868, 0.57857132],
       [0.30538941, 0.69461059],
       [0.71221976, 0.28778024],
       [0.77790972, 0.22209028],
       [0.7938926 , 0.2061074 ],
       [0.42422877, 0.57577123],
       [0.63561337, 0.36438663],
       [0.33103371, 0.66896629],
       [0.72871439, 0.27128561],
       [0.16665264, 0.83334736],
       [0.56600768, 0.43399232],
       [0.11399337, 0.88600663],
       [0.76603645, 0.23396355],
       [0.62829315, 0.37170685],
       [0.61790495, 0.38209505],
       [0.30203861, 0.69796139],
       [0.34090197, 0.65909803],
       [0.70607803, 0.29392197],
       [0.20313854, 0.79686146],
       [0.79043907, 0.20956093],
       [0.7300077 , 0.2699923 ],
       [0.89600113, 0.10399887],
       [0.77546993, 0.22453007],
       [0.26055756, 0.73944244],
       [0.69918168, 0.30081832],
       [0.77546993, 0.22453007],
       [0.67311234, 0.32688766],
       [0.09662446, 0.90337554],
       [0.54254271, 0.45745729],
       [0.40002753, 0.59997247],
       [0.77903962, 0.22096038],
       [0.22136985, 0.77863015],
       [0.27141023, 0.72858977],
       [0.25655446, 0.74344554],
       [0.32955172, 0.67044828],
       [0.75152292, 0.24847708],
       [0.91016537, 0.08983463],
       [0.76603645, 0.23396355],
       [0.24559275, 0.75440725],
       [0.5662996 , 0.4337004 ],
       [0.87737541, 0.12262459],
       [0.29308287, 0.70691713],
       [0.41634563, 0.58365437],
       [0.72586122, 0.27413878],
       [0.31683213, 0.68316787],
       [0.82638206, 0.17361794],
       [0.84738944, 0.15261056],
       [0.77133106, 0.22866894],
       [0.7300077 , 0.2699923 ],
       [0.74708659, 0.25291341],
       [0.14880137, 0.85119863],
       [0.70306858, 0.29693142],
       [0.23583473, 0.76416527],
       [0.75414044, 0.24585956],
       [0.7849557 , 0.2150443 ],
       [0.37899345, 0.62100655],
       [0.31683213, 0.68316787],
       [0.3009509 , 0.6990491 ],
       [0.25754083, 0.74245917],
       [0.55349928, 0.44650072],
       [0.52051622, 0.47948378],
       [0.72120075, 0.27879925],
       [0.14880137, 0.85119863],
       [0.22409477, 0.77590523],
       [0.85302259, 0.14697741],
       [0.91714155, 0.08285845],
       [0.09654353, 0.90345647],
       [0.3277294 , 0.6722706 ],
       [0.66009241, 0.33990759],
       [0.47609389, 0.52390611],
       [0.44001423, 0.55998577],
       [0.20887576, 0.79112424],
       [0.1783463 , 0.8216537 ],
       [0.45533557, 0.54466443],
       [0.6893534 , 0.3106466 ],
       [0.73863728, 0.26136272],
       [0.8399901 , 0.1600099 ],
       [0.19001459, 0.80998541],
       [0.54516654, 0.45483346],
       [0.77903962, 0.22096038],
       [0.65072406, 0.34927594],
       [0.78656024, 0.21343976],
       [0.88776978, 0.11223022],
       [0.25780614, 0.74219386],
       [0.69874615, 0.30125385],
       [0.3864439 , 0.6135561 ],
       [0.78656024, 0.21343976],
       [0.70306858, 0.29693142],
       [0.65072406, 0.34927594],
       [0.73284787, 0.26715213],
       [0.47609389, 0.52390611],
       [0.53930442, 0.46069558],
       [0.68979648, 0.31020352],
       [0.75414044, 0.24585956],
       [0.54254271, 0.45745729]])

In [53]:
predicted_proba.shape

(140, 2)

In [54]:
# select ONLY the probabilities referring to 1s
predicted_proba[:,1]

array([0.28778024, 0.41239991, 0.55662562, 0.22096038, 0.91541657,
       0.66896629, 0.70207504, 0.87043779, 0.21692179, 0.25291341,
       0.50485031, 0.77359703, 0.92969016, 0.26495948, 0.69466915,
       0.44964119, 0.44972574, 0.46069558, 0.59882226, 0.94679318,
       0.30125385, 0.22096038, 0.58365437, 0.58365437, 0.7587085 ,
       0.25682913, 0.48934806, 0.14296697, 0.80065765, 0.22096038,
       0.37028423, 0.68316787, 0.68825755, 0.52694241, 0.22096038,
       0.53492642, 0.22453007, 0.74389237, 0.40329273, 0.60301627,
       0.21343976, 0.45483346, 0.2403088 , 0.4388431 , 0.82622935,
       0.57857132, 0.69461059, 0.28778024, 0.22209028, 0.2061074 ,
       0.57577123, 0.36438663, 0.66896629, 0.27128561, 0.83334736,
       0.43399232, 0.88600663, 0.23396355, 0.37170685, 0.38209505,
       0.69796139, 0.65909803, 0.29392197, 0.79686146, 0.20956093,
       0.2699923 , 0.10399887, 0.22453007, 0.73944244, 0.30081832,
       0.22453007, 0.32688766, 0.90337554, 0.45745729, 0.59997247,
       0.22096038, 0.77863015, 0.72858977, 0.74344554, 0.67044828,
       0.24847708, 0.08983463, 0.23396355, 0.75440725, 0.4337004 ,
       0.12262459, 0.70691713, 0.58365437, 0.27413878, 0.68316787,
       0.17361794, 0.15261056, 0.22866894, 0.2699923 , 0.25291341,
       0.85119863, 0.29693142, 0.76416527, 0.24585956, 0.2150443 ,
       0.62100655, 0.68316787, 0.6990491 , 0.74245917, 0.44650072,
       0.47948378, 0.27879925, 0.85119863, 0.77590523, 0.14697741,
       0.08285845, 0.90345647, 0.6722706 , 0.33990759, 0.52390611,
       0.55998577, 0.79112424, 0.8216537 , 0.54466443, 0.3106466 ,
       0.26136272, 0.1600099 , 0.80998541, 0.45483346, 0.22096038,
       0.34927594, 0.21343976, 0.11223022, 0.74219386, 0.30125385,
       0.6135561 , 0.21343976, 0.29693142, 0.34927594, 0.26715213,
       0.52390611, 0.46069558, 0.31020352, 0.24585956, 0.45745729])

## Save the model

In [55]:
# import the relevant module
import pickle

In [56]:
# pickle the model file
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [57]:
# pickle the scaler file
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)